name: "10.02.lab01 deploy"

on:
  push:             #trigger: push 시
    branches: [main]
    paths: ["ch10/02/lab01/infra/*.tf"]

permissions:
  contents: read
  id-token: write
  pull-requests: write

concurrency:
  group: tf-core-10.02.loab01-deploy
  cancel-in-progress: false

env:
  TF_VERSION: "1.15.2"
  AWS_REGION: "ap-northeast-2"
  WORKING_DIR: "ch10/02/lab01/infra"

jobs:
  my_apply:           #job 정의
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_IAMROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve